package com.easy2excel.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.nio.ByteBuffer;

@DynamoDBTable(tableName="facerecognition")
public class Facerecognition {
	@DynamoDBHashKey(attributeName = "RekognitionId")
	@DynamoDBAutoGeneratedKey
	private String RekognitionId;
	
    @DynamoDBAttribute(attributeName = "image")
	private ByteBuffer image;

	public String getRekognitionId() {
		return RekognitionId;
	}

	public void setRekognitionId(String rekognitionId) {
		RekognitionId = rekognitionId;
	}

	public ByteBuffer getImage() {
		return image;
	}

	public void setImage(ByteBuffer image) {
		this.image = image;
	}

	
    
}
